# Generated by Django 5.0.6 on 2024-07-08 12:33

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/app/mediafiles/screenshots'), upload_to=''),
        ),
    ]
